### ISSUE TITLE
Error: Cannot find module '../../../'

### ISSUE THREAD

**Issue by mxmilkiib** [shokai/korg-nano-kontrol#11]
`npm run buildSample` gives me
```
> korg-nano-kontrol@0.2.9 buildSample /home/milk/src/korg-nano-kontrol
> browserify --debug samples/webmidi/src/main.js -o samples/webmidi/dist/bundle.js

Error: Cannot find module '../../../' from '/home/milk/src/korg-nano-kontrol/samples/webmidi/src'
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:166:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! korg-nano-kontrol@0.2.9 buildSample: `browserify --debug samples/webmidi/src/main.js -o samples/webmidi/dist/bundle.js`
npm ERR! Exit status 1
```

**Comment by cyrildiagne** [comment]
Problem was solved after running "npm install" and "npm run build".
